config/routes.rb
Rails.application.routes.draw do

  
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'subjects#index', as: :authenticated_root
  end
end

 resources :demos
  root 'demos#index'
  resources :subjects do
    member do 
       get :delete
  end
end

  resources :photos
  get 'demo/index'
  get 'demo/hello'
  get 'demo/hello1'
  get 'demo/youtube'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class Admin_Users < ApplicationRecord
  # self.table_name ="admin_users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :subject

  scope :visible, lambda {where(:visible => true)}
  scope :invisible, lambda{where(:visible => false)}
  scope :sorted, lambda{order("position ASC")}
 
  scope :newest_first, lambda{order("position DESC")}
  scope :search, lambda{|query| where{["name LIKE ?" , "%#{query}%"]}}
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
   has_many :pages
   
  scope :visible, lambda {where(:visible => true)}
  scope :invisible, lambda{where(:visible => false)}
  scope :sorted, lambda{order("position ASC")}
  scope :search, lambda{|query| where{["name LIKE ?" , "%#{query}%"]}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 

    
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController

  def index
    @photos =Photos.all
  end
  

  def hello
    @array = [1,2,3,3,4,45,55,5,56,]
    render ('hello')
  end


  def hello1
    # redirect_to(:controller=>"demo", :action=>"index")
    redirect_to( :action=>"index")
  end

  def youtube
    redirect_to('http://youtube.com')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def index
    @pages =Page.sorted
  end
  
  def show
     @page =Page.find(params[:id])
  end

  def new
    @page =Page.new
  end

  def create
    @page= Page.new(page_params)
   if @page.save
    flash[:notice] = "page created successfully...."
    redirect_to(pages_path)
  else
    render 'new'
  end
  end

  def edit
    @page =Page.find(params[:id])
  end

  def update
        @page =Page.find(params[:id])
    
   if @page.update_attributes(page_params)
    flash[:notice] = "page updated successfully...."
    redirect_to(page_path(@page))
  else
   render ('edit')
  end
end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
   @page = Page.find(params[:id])
   @page.destroy
   flash[:notice] = "page '#{@page.name}' delete successfully...."
   redirect_to (pages_path)
  end

  private
  def page_params
 params.required(:page).permit(:subject_id,:name,:position,:permalink,:visible,)
  end
end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :image, :remove_image)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!
  def index
    @subjects =Subject.sorted
  end
  
  def show
     @subject =Subject.find(params[:id])
  end

  def new
    @subject =Subject.new
  end

  def create
    @subject= Subject.new(subject_params)
   if @subject.save
    flash[:notice] = "subject created successfully...."
    redirect_to(subjects_path)
  else
    render 'new'
  end
  end

  def edit
    @subject =Subject.find(params[:id])
  end

  def update
    @subject =Subject.find(params[:id])
    
   if @subject.update_attributes(subject_params)
    flash[:notice] = "subject updated successfully...."
    redirect_to(subject_path(@subject))
  else
   render ('edit')
  end
end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
   @subject = Subject.find(params[:id])
   @subject.destroy
   flash[:notice] = "subject '#{@subject.name}' delete successfully...."
   redirect_to (subjects_path)
  end

  private
  def subject_params
 params.required(:subject).permit(:name,:position,:visible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demos/hello.html.erb
<h1>hello word</h1>
<% var = "kanchan" %>
<%= "hello #{var}"%>
<% @array.each do |n|%>
<%= n %><br>
<%end%>

app/views/demos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<div>
  <% @photos.each do |photo| %>       
    <%= link_to(image_tag(attachment_url(photo, :image, :fit, 100, 100, format: 'jpg')), attachment_url(photo, :image, :fit, 500, 500, format: 'jpg'), data: { lightbox: "example-set", title: photo.name }) %>     
  <% end %>
</div>    

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Album</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page, :html => { :class => "form-horizontal page" } do |f| %>

  <% if @page.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :subject_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :subject_id, :class => 'form-control' %>
    </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :permalink, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :permalink, :class => 'form-control' %>
    </div>

  <div class="form-group">
    <%= f.label :position, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :position, :class => 'form-control' %>
    </div>
    <%=f.error_span(:position) %>
  </div>

  <div class="form-group">
    <%= f.label :visible, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :visible, :class => 'form-control' %>
    </div>
   </div>
  
    
   
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pages_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<script type="text/javascript">
   $(document).ready(function(){
    $(".ckeditor").ckeditor({});
   });
 </script>

app/views/pages/delete.html.erb
<%= link_to("Back To List", pages_path , :class =>'back-link')%>
<div class="page delete">
<h1>Delete  page</h1>

<%= form_for(@page,:url => page_path(@page),:method => 'delete')do |f|%>
<p>Are You Sure you want to delete this subject</p>
<p class="reference-name"><%= @page.name%></p>
<div class="form-button">
<%= f.submit('Delete page')%>
</div>
<%end%>
</div>

app/views/pages/edit.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pages/index.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
       <th><%= model_class.human_attribute_name(:subject_id) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:permalink) %></th>
      <th><%= model_class.human_attribute_name(:visible) %></th>
 
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.id, page_path(page) %></td>
        <td><%= page.name %></td>
        <td><%= page.position %></td>
        <td><%= page.visible %></td>
        <td><%= page.permalink %></td>
         <td><%= page.subject_id %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      page_path(page), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_page_path(page), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      page_path(page),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_page_path,
            :class => 'btn btn-primary' %>

app/views/pages/new.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pages/show.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:subject_id) %>:</strong></dt>
 <dd><%= @page.subject_id %></dd>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @page.name %></dd>

  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @page.position %></dd>

   <dt><strong><%= model_class.human_attribute_name(:permalink) %>:</strong></dt>
  <dd><%= @page.permalink %></dd>

  <dt><strong><%= model_class.human_attribute_name(:visible) %>:</strong></dt>
  <dd><%= @page.visible %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pages_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_page_path(@page), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              page_path(@page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :class => "form-horizontal photo" } do |f| %>

  <% if @photo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :image_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image_id) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                photos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<h3>A Four Image Set</h3>
  <div>
      <a class="example-image-link" href="assets/img1.jpg" data-lightbox="example-set" data-title="Click the right half of the image to move forward.">
      <img class="example-image" src="assets/thumb-3.jpg" alt=""/></a>
      <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-4.jpg" data-lightbox="example-set" data-title="Or press the right arrow on your keyboard."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-4.jpg" alt="" /></a>
      <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-5.jpg" data-lightbox="example-set" data-title="The next image in the set is preloaded as you're viewing."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-5.jpg" alt="" /></a>
      <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-6.jpg" data-lightbox="example-set" data-title="Click anywhere outside the image or the X to the right to close."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-6.jpg" alt="" /></a>
  </div>
</section>

<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:image_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.id, photo_path(photo) %></td>
        <td><%= photo.image_id %></td>
        <td><%= photo.name %></td>
        <td><%=l photo.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      photo_path(photo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_photo_path(photo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      photo_path(photo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_photo_path,
            :class => 'btn btn-primary' %>

app/views/photos/new.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/show.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image_id) %>:</strong></dt>
  <dd><%= @photo.image_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @photo.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              photos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_photo_path(@photo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              photo_path(@photo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/subjects/_form.html.erb
<%= form_for @subject, :html => { :class => "form-horizontal subject" } do |f| %>

  <% if @subject.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :position, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :position, :class => 'form-control' %>
    </div>
    <%=f.error_span(:position) %>
  </div>
  <div class="form-group">
    <%= f.label :visible, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :visible, :class => 'form-control' %>
    </div>
   </div>
   <br> 
    
   <div class="form-group">
    <%= f.label :details, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :details, :class => 'form-control ckeditor' %>
    </div>
    <%=f.error_span(:details) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                subjects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<script type="text/javascript">
   $(document).ready(function(){
    $(".ckeditor").ckeditor({});
   });
 </script>

app/views/subjects/delete.html.erb
<%= link_to("Back To List", subjects_path , :class =>'back-link')%>
<div class="subject delete">
<h1>Delete  Subject</h1>

<%= form_for(@subject,:url => subject_path(@subject),:method => 'delete')do |f|%>
<p>Are You Sure you want to delete this subject</p>
<p class="reference-name"><%= @subject.name%></p>
<div class="form-button">
<%= f.submit('Delete Subject')%>
</div>
<%end%>
</div>

app/views/subjects/edit.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/index.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:visible) %></th>
 
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= link_to subject.id, subject_path(subject) %></td>
        <td><%= subject.name %></td>
        <td><%= subject.position %></td>
        <td><%= subject.visible %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      subject_path(subject), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subject_path(subject), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subject_path(subject),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_path,
            :class => 'btn btn-primary' %>

app/views/subjects/new.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/show.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @subject.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @subject.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:visible) %>:</strong></dt>
  <dd><%= @subject.visible %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              subjects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subject_path(@subject), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subject_path(@subject),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>